/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutHomeIndexImport } from './routes/_layout/home/index'
import { Route as LayoutHomeVaccinationImport } from './routes/_layout/home/vaccination'
import { Route as LayoutHomeUserProfileImport } from './routes/_layout/home/user-profile'
import { Route as LayoutHomeManageFamilyImport } from './routes/_layout/home/manage-family'
import { Route as LayoutHomeDocumentsImport } from './routes/_layout/home/documents'
import { Route as LayoutHomeHealthProfileIndexImport } from './routes/_layout/home/health-profile/index'
import { Route as LayoutHomeFamiliesIndexImport } from './routes/_layout/home/families/index'
import { Route as LayoutHomeFamiliesSharingIndexImport } from './routes/_layout/home/families/sharing/index'
import { Route as LayoutHomeFamiliesFamilyIdIndexImport } from './routes/_layout/home/families/$familyId/index'
import { Route as LayoutHomeRecordsIdPrescriptionImport } from './routes/_layout/home/records/$id/prescription'
import { Route as LayoutHomeFamiliesFamilyIdMembersMemberIdImport } from './routes/_layout/home/families/$familyId/members/$memberId'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutHomeIndexRoute = LayoutHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeVaccinationRoute = LayoutHomeVaccinationImport.update({
  id: '/home/vaccination',
  path: '/home/vaccination',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeUserProfileRoute = LayoutHomeUserProfileImport.update({
  id: '/home/user-profile',
  path: '/home/user-profile',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeManageFamilyRoute = LayoutHomeManageFamilyImport.update({
  id: '/home/manage-family',
  path: '/home/manage-family',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeDocumentsRoute = LayoutHomeDocumentsImport.update({
  id: '/home/documents',
  path: '/home/documents',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeHealthProfileIndexRoute =
  LayoutHomeHealthProfileIndexImport.update({
    id: '/home/health-profile/',
    path: '/home/health-profile/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutHomeFamiliesIndexRoute = LayoutHomeFamiliesIndexImport.update({
  id: '/home/families/',
  path: '/home/families/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeFamiliesSharingIndexRoute =
  LayoutHomeFamiliesSharingIndexImport.update({
    id: '/home/families/sharing/',
    path: '/home/families/sharing/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutHomeFamiliesFamilyIdIndexRoute =
  LayoutHomeFamiliesFamilyIdIndexImport.update({
    id: '/home/families/$familyId/',
    path: '/home/families/$familyId/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutHomeRecordsIdPrescriptionRoute =
  LayoutHomeRecordsIdPrescriptionImport.update({
    id: '/home/records/$id/prescription',
    path: '/home/records/$id/prescription',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutHomeFamiliesFamilyIdMembersMemberIdRoute =
  LayoutHomeFamiliesFamilyIdMembersMemberIdImport.update({
    id: '/home/families/$familyId/members/$memberId',
    path: '/home/families/$familyId/members/$memberId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_layout/home/documents': {
      id: '/_layout/home/documents'
      path: '/home/documents'
      fullPath: '/home/documents'
      preLoaderRoute: typeof LayoutHomeDocumentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/manage-family': {
      id: '/_layout/home/manage-family'
      path: '/home/manage-family'
      fullPath: '/home/manage-family'
      preLoaderRoute: typeof LayoutHomeManageFamilyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/user-profile': {
      id: '/_layout/home/user-profile'
      path: '/home/user-profile'
      fullPath: '/home/user-profile'
      preLoaderRoute: typeof LayoutHomeUserProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/vaccination': {
      id: '/_layout/home/vaccination'
      path: '/home/vaccination'
      fullPath: '/home/vaccination'
      preLoaderRoute: typeof LayoutHomeVaccinationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/families/': {
      id: '/_layout/home/families/'
      path: '/home/families'
      fullPath: '/home/families'
      preLoaderRoute: typeof LayoutHomeFamiliesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/health-profile/': {
      id: '/_layout/home/health-profile/'
      path: '/home/health-profile'
      fullPath: '/home/health-profile'
      preLoaderRoute: typeof LayoutHomeHealthProfileIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/records/$id/prescription': {
      id: '/_layout/home/records/$id/prescription'
      path: '/home/records/$id/prescription'
      fullPath: '/home/records/$id/prescription'
      preLoaderRoute: typeof LayoutHomeRecordsIdPrescriptionImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/families/$familyId/': {
      id: '/_layout/home/families/$familyId/'
      path: '/home/families/$familyId'
      fullPath: '/home/families/$familyId'
      preLoaderRoute: typeof LayoutHomeFamiliesFamilyIdIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/families/sharing/': {
      id: '/_layout/home/families/sharing/'
      path: '/home/families/sharing'
      fullPath: '/home/families/sharing'
      preLoaderRoute: typeof LayoutHomeFamiliesSharingIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/families/$familyId/members/$memberId': {
      id: '/_layout/home/families/$familyId/members/$memberId'
      path: '/home/families/$familyId/members/$memberId'
      fullPath: '/home/families/$familyId/members/$memberId'
      preLoaderRoute: typeof LayoutHomeFamiliesFamilyIdMembersMemberIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutHomeDocumentsRoute: typeof LayoutHomeDocumentsRoute
  LayoutHomeManageFamilyRoute: typeof LayoutHomeManageFamilyRoute
  LayoutHomeUserProfileRoute: typeof LayoutHomeUserProfileRoute
  LayoutHomeVaccinationRoute: typeof LayoutHomeVaccinationRoute
  LayoutHomeIndexRoute: typeof LayoutHomeIndexRoute
  LayoutHomeFamiliesIndexRoute: typeof LayoutHomeFamiliesIndexRoute
  LayoutHomeHealthProfileIndexRoute: typeof LayoutHomeHealthProfileIndexRoute
  LayoutHomeRecordsIdPrescriptionRoute: typeof LayoutHomeRecordsIdPrescriptionRoute
  LayoutHomeFamiliesFamilyIdIndexRoute: typeof LayoutHomeFamiliesFamilyIdIndexRoute
  LayoutHomeFamiliesSharingIndexRoute: typeof LayoutHomeFamiliesSharingIndexRoute
  LayoutHomeFamiliesFamilyIdMembersMemberIdRoute: typeof LayoutHomeFamiliesFamilyIdMembersMemberIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHomeDocumentsRoute: LayoutHomeDocumentsRoute,
  LayoutHomeManageFamilyRoute: LayoutHomeManageFamilyRoute,
  LayoutHomeUserProfileRoute: LayoutHomeUserProfileRoute,
  LayoutHomeVaccinationRoute: LayoutHomeVaccinationRoute,
  LayoutHomeIndexRoute: LayoutHomeIndexRoute,
  LayoutHomeFamiliesIndexRoute: LayoutHomeFamiliesIndexRoute,
  LayoutHomeHealthProfileIndexRoute: LayoutHomeHealthProfileIndexRoute,
  LayoutHomeRecordsIdPrescriptionRoute: LayoutHomeRecordsIdPrescriptionRoute,
  LayoutHomeFamiliesFamilyIdIndexRoute: LayoutHomeFamiliesFamilyIdIndexRoute,
  LayoutHomeFamiliesSharingIndexRoute: LayoutHomeFamiliesSharingIndexRoute,
  LayoutHomeFamiliesFamilyIdMembersMemberIdRoute:
    LayoutHomeFamiliesFamilyIdMembersMemberIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/documents': typeof LayoutHomeDocumentsRoute
  '/home/manage-family': typeof LayoutHomeManageFamilyRoute
  '/home/user-profile': typeof LayoutHomeUserProfileRoute
  '/home/vaccination': typeof LayoutHomeVaccinationRoute
  '/home': typeof LayoutHomeIndexRoute
  '/home/families': typeof LayoutHomeFamiliesIndexRoute
  '/home/health-profile': typeof LayoutHomeHealthProfileIndexRoute
  '/home/records/$id/prescription': typeof LayoutHomeRecordsIdPrescriptionRoute
  '/home/families/$familyId': typeof LayoutHomeFamiliesFamilyIdIndexRoute
  '/home/families/sharing': typeof LayoutHomeFamiliesSharingIndexRoute
  '/home/families/$familyId/members/$memberId': typeof LayoutHomeFamiliesFamilyIdMembersMemberIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/home/documents': typeof LayoutHomeDocumentsRoute
  '/home/manage-family': typeof LayoutHomeManageFamilyRoute
  '/home/user-profile': typeof LayoutHomeUserProfileRoute
  '/home/vaccination': typeof LayoutHomeVaccinationRoute
  '/home': typeof LayoutHomeIndexRoute
  '/home/families': typeof LayoutHomeFamiliesIndexRoute
  '/home/health-profile': typeof LayoutHomeHealthProfileIndexRoute
  '/home/records/$id/prescription': typeof LayoutHomeRecordsIdPrescriptionRoute
  '/home/families/$familyId': typeof LayoutHomeFamiliesFamilyIdIndexRoute
  '/home/families/sharing': typeof LayoutHomeFamiliesSharingIndexRoute
  '/home/families/$familyId/members/$memberId': typeof LayoutHomeFamiliesFamilyIdMembersMemberIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/home/documents': typeof LayoutHomeDocumentsRoute
  '/_layout/home/manage-family': typeof LayoutHomeManageFamilyRoute
  '/_layout/home/user-profile': typeof LayoutHomeUserProfileRoute
  '/_layout/home/vaccination': typeof LayoutHomeVaccinationRoute
  '/_layout/home/': typeof LayoutHomeIndexRoute
  '/_layout/home/families/': typeof LayoutHomeFamiliesIndexRoute
  '/_layout/home/health-profile/': typeof LayoutHomeHealthProfileIndexRoute
  '/_layout/home/records/$id/prescription': typeof LayoutHomeRecordsIdPrescriptionRoute
  '/_layout/home/families/$familyId/': typeof LayoutHomeFamiliesFamilyIdIndexRoute
  '/_layout/home/families/sharing/': typeof LayoutHomeFamiliesSharingIndexRoute
  '/_layout/home/families/$familyId/members/$memberId': typeof LayoutHomeFamiliesFamilyIdMembersMemberIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/home/documents'
    | '/home/manage-family'
    | '/home/user-profile'
    | '/home/vaccination'
    | '/home'
    | '/home/families'
    | '/home/health-profile'
    | '/home/records/$id/prescription'
    | '/home/families/$familyId'
    | '/home/families/sharing'
    | '/home/families/$familyId/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/home/documents'
    | '/home/manage-family'
    | '/home/user-profile'
    | '/home/vaccination'
    | '/home'
    | '/home/families'
    | '/home/health-profile'
    | '/home/records/$id/prescription'
    | '/home/families/$familyId'
    | '/home/families/sharing'
    | '/home/families/$familyId/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_layout/home/documents'
    | '/_layout/home/manage-family'
    | '/_layout/home/user-profile'
    | '/_layout/home/vaccination'
    | '/_layout/home/'
    | '/_layout/home/families/'
    | '/_layout/home/health-profile/'
    | '/_layout/home/records/$id/prescription'
    | '/_layout/home/families/$familyId/'
    | '/_layout/home/families/sharing/'
    | '/_layout/home/families/$familyId/members/$memberId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about",
        "/forgot-password",
        "/login",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/home/documents",
        "/_layout/home/manage-family",
        "/_layout/home/user-profile",
        "/_layout/home/vaccination",
        "/_layout/home/",
        "/_layout/home/families/",
        "/_layout/home/health-profile/",
        "/_layout/home/records/$id/prescription",
        "/_layout/home/families/$familyId/",
        "/_layout/home/families/sharing/",
        "/_layout/home/families/$familyId/members/$memberId"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_layout/home/documents": {
      "filePath": "_layout/home/documents.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/manage-family": {
      "filePath": "_layout/home/manage-family.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/user-profile": {
      "filePath": "_layout/home/user-profile.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/vaccination": {
      "filePath": "_layout/home/vaccination.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/": {
      "filePath": "_layout/home/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/families/": {
      "filePath": "_layout/home/families/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/health-profile/": {
      "filePath": "_layout/home/health-profile/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/records/$id/prescription": {
      "filePath": "_layout/home/records/$id/prescription.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/families/$familyId/": {
      "filePath": "_layout/home/families/$familyId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/families/sharing/": {
      "filePath": "_layout/home/families/sharing/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/families/$familyId/members/$memberId": {
      "filePath": "_layout/home/families/$familyId/members/$memberId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
